project:
  type: website
  output-dir: docs

website:
  page-footer:
    left: "R"
    right:
      - icon: github
        href: https://github.com/rxckxtx
    
  title: "Ricardo Arana"
  
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: resume.qmd
        text: Resume
      - href: gallery.qmd
        text: Gallery

format:
  html:
    theme: lux
    css: styles.css
    toc: true



